/*
 * This file is generated by jOOQ.
 */
package com.github.chaconne.jooq;


import com.github.chaconne.jooq.tables.CronTaskDetail;
import com.github.chaconne.jooq.tables.CronTaskLog;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>cron_task_detail</code>.
     */
    public static final CronTaskDetail CRON_TASK_DETAIL = CronTaskDetail.CRON_TASK_DETAIL;

    /**
     * The table <code>cron_task_log</code>.
     */
    public static final CronTaskLog CRON_TASK_LOG = CronTaskLog.CRON_TASK_LOG;
}
