/*
 * This file is generated by jOOQ.
 */
package com.github.chaconne.jooq.tables.records;


import com.github.chaconne.jooq.tables.CronTaskLog;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CronTaskLogRecord extends TableRecordImpl<CronTaskLogRecord> implements Record10<String, String, String, String, String, String, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cron_task_log.task_name</code>.
     */
    public CronTaskLogRecord setTaskName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>cron_task_log.task_name</code>.
     */
    public String getTaskName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>cron_task_log.task_group</code>.
     */
    public CronTaskLogRecord setTaskGroup(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>cron_task_log.task_group</code>.
     */
    public String getTaskGroup() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cron_task_log.task_class</code>.
     */
    public CronTaskLogRecord setTaskClass(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>cron_task_log.task_class</code>.
     */
    public String getTaskClass() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cron_task_log.task_method</code>.
     */
    public CronTaskLogRecord setTaskMethod(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>cron_task_log.task_method</code>.
     */
    public String getTaskMethod() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cron_task_log.initial_parameter</code>.
     */
    public CronTaskLogRecord setInitialParameter(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>cron_task_log.initial_parameter</code>.
     */
    public String getInitialParameter() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cron_task_log.task_status</code>.
     */
    public CronTaskLogRecord setTaskStatus(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>cron_task_log.task_status</code>.
     */
    public String getTaskStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cron_task_log.log_level</code>.
     */
    public CronTaskLogRecord setLogLevel(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>cron_task_log.log_level</code>.
     */
    public String getLogLevel() {
        return (String) get(6);
    }

    /**
     * Setter for <code>cron_task_log.message</code>.
     */
    public CronTaskLogRecord setMessage(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>cron_task_log.message</code>.
     */
    public String getMessage() {
        return (String) get(7);
    }

    /**
     * Setter for <code>cron_task_log.error_detail</code>.
     */
    public CronTaskLogRecord setErrorDetail(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>cron_task_log.error_detail</code>.
     */
    public String getErrorDetail() {
        return (String) get(8);
    }

    /**
     * Setter for <code>cron_task_log.log_datetime</code>.
     */
    public CronTaskLogRecord setLogDatetime(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>cron_task_log.log_datetime</code>.
     */
    public LocalDateTime getLogDatetime() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<String, String, String, String, String, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<String, String, String, String, String, String, String, String, String, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return CronTaskLog.CRON_TASK_LOG.TASK_NAME;
    }

    @Override
    public Field<String> field2() {
        return CronTaskLog.CRON_TASK_LOG.TASK_GROUP;
    }

    @Override
    public Field<String> field3() {
        return CronTaskLog.CRON_TASK_LOG.TASK_CLASS;
    }

    @Override
    public Field<String> field4() {
        return CronTaskLog.CRON_TASK_LOG.TASK_METHOD;
    }

    @Override
    public Field<String> field5() {
        return CronTaskLog.CRON_TASK_LOG.INITIAL_PARAMETER;
    }

    @Override
    public Field<String> field6() {
        return CronTaskLog.CRON_TASK_LOG.TASK_STATUS;
    }

    @Override
    public Field<String> field7() {
        return CronTaskLog.CRON_TASK_LOG.LOG_LEVEL;
    }

    @Override
    public Field<String> field8() {
        return CronTaskLog.CRON_TASK_LOG.MESSAGE;
    }

    @Override
    public Field<String> field9() {
        return CronTaskLog.CRON_TASK_LOG.ERROR_DETAIL;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return CronTaskLog.CRON_TASK_LOG.LOG_DATETIME;
    }

    @Override
    public String component1() {
        return getTaskName();
    }

    @Override
    public String component2() {
        return getTaskGroup();
    }

    @Override
    public String component3() {
        return getTaskClass();
    }

    @Override
    public String component4() {
        return getTaskMethod();
    }

    @Override
    public String component5() {
        return getInitialParameter();
    }

    @Override
    public String component6() {
        return getTaskStatus();
    }

    @Override
    public String component7() {
        return getLogLevel();
    }

    @Override
    public String component8() {
        return getMessage();
    }

    @Override
    public String component9() {
        return getErrorDetail();
    }

    @Override
    public LocalDateTime component10() {
        return getLogDatetime();
    }

    @Override
    public String value1() {
        return getTaskName();
    }

    @Override
    public String value2() {
        return getTaskGroup();
    }

    @Override
    public String value3() {
        return getTaskClass();
    }

    @Override
    public String value4() {
        return getTaskMethod();
    }

    @Override
    public String value5() {
        return getInitialParameter();
    }

    @Override
    public String value6() {
        return getTaskStatus();
    }

    @Override
    public String value7() {
        return getLogLevel();
    }

    @Override
    public String value8() {
        return getMessage();
    }

    @Override
    public String value9() {
        return getErrorDetail();
    }

    @Override
    public LocalDateTime value10() {
        return getLogDatetime();
    }

    @Override
    public CronTaskLogRecord value1(String value) {
        setTaskName(value);
        return this;
    }

    @Override
    public CronTaskLogRecord value2(String value) {
        setTaskGroup(value);
        return this;
    }

    @Override
    public CronTaskLogRecord value3(String value) {
        setTaskClass(value);
        return this;
    }

    @Override
    public CronTaskLogRecord value4(String value) {
        setTaskMethod(value);
        return this;
    }

    @Override
    public CronTaskLogRecord value5(String value) {
        setInitialParameter(value);
        return this;
    }

    @Override
    public CronTaskLogRecord value6(String value) {
        setTaskStatus(value);
        return this;
    }

    @Override
    public CronTaskLogRecord value7(String value) {
        setLogLevel(value);
        return this;
    }

    @Override
    public CronTaskLogRecord value8(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public CronTaskLogRecord value9(String value) {
        setErrorDetail(value);
        return this;
    }

    @Override
    public CronTaskLogRecord value10(LocalDateTime value) {
        setLogDatetime(value);
        return this;
    }

    @Override
    public CronTaskLogRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CronTaskLogRecord
     */
    public CronTaskLogRecord() {
        super(CronTaskLog.CRON_TASK_LOG);
    }

    /**
     * Create a detached, initialised CronTaskLogRecord
     */
    public CronTaskLogRecord(String taskName, String taskGroup, String taskClass, String taskMethod, String initialParameter, String taskStatus, String logLevel, String message, String errorDetail, LocalDateTime logDatetime) {
        super(CronTaskLog.CRON_TASK_LOG);

        setTaskName(taskName);
        setTaskGroup(taskGroup);
        setTaskClass(taskClass);
        setTaskMethod(taskMethod);
        setInitialParameter(initialParameter);
        setTaskStatus(taskStatus);
        setLogLevel(logLevel);
        setMessage(message);
        setErrorDetail(errorDetail);
        setLogDatetime(logDatetime);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CronTaskLogRecord
     */
    public CronTaskLogRecord(com.github.chaconne.jooq.tables.pojos.CronTaskLog value) {
        super(CronTaskLog.CRON_TASK_LOG);

        if (value != null) {
            setTaskName(value.getTaskName());
            setTaskGroup(value.getTaskGroup());
            setTaskClass(value.getTaskClass());
            setTaskMethod(value.getTaskMethod());
            setInitialParameter(value.getInitialParameter());
            setTaskStatus(value.getTaskStatus());
            setLogLevel(value.getLogLevel());
            setMessage(value.getMessage());
            setErrorDetail(value.getErrorDetail());
            setLogDatetime(value.getLogDatetime());
            resetChangedOnNotNull();
        }
    }
}
