/*
 * This file is generated by jOOQ.
 */
package com.github.chaconne.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CronTaskQueue implements Serializable {

    private static final long serialVersionUID = 1L;

    private LocalDateTime firedDatetime;
    private String taskName;
    private String taskGroup;

    public CronTaskQueue() {}

    public CronTaskQueue(CronTaskQueue value) {
        this.firedDatetime = value.firedDatetime;
        this.taskName = value.taskName;
        this.taskGroup = value.taskGroup;
    }

    public CronTaskQueue(
        LocalDateTime firedDatetime,
        String taskName,
        String taskGroup
    ) {
        this.firedDatetime = firedDatetime;
        this.taskName = taskName;
        this.taskGroup = taskGroup;
    }

    /**
     * Getter for <code>cron_task_queue.fired_datetime</code>.
     */
    public LocalDateTime getFiredDatetime() {
        return this.firedDatetime;
    }

    /**
     * Setter for <code>cron_task_queue.fired_datetime</code>.
     */
    public CronTaskQueue setFiredDatetime(LocalDateTime firedDatetime) {
        this.firedDatetime = firedDatetime;
        return this;
    }

    /**
     * Getter for <code>cron_task_queue.task_name</code>.
     */
    public String getTaskName() {
        return this.taskName;
    }

    /**
     * Setter for <code>cron_task_queue.task_name</code>.
     */
    public CronTaskQueue setTaskName(String taskName) {
        this.taskName = taskName;
        return this;
    }

    /**
     * Getter for <code>cron_task_queue.task_group</code>.
     */
    public String getTaskGroup() {
        return this.taskGroup;
    }

    /**
     * Setter for <code>cron_task_queue.task_group</code>.
     */
    public CronTaskQueue setTaskGroup(String taskGroup) {
        this.taskGroup = taskGroup;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CronTaskQueue other = (CronTaskQueue) obj;
        if (this.firedDatetime == null) {
            if (other.firedDatetime != null)
                return false;
        }
        else if (!this.firedDatetime.equals(other.firedDatetime))
            return false;
        if (this.taskName == null) {
            if (other.taskName != null)
                return false;
        }
        else if (!this.taskName.equals(other.taskName))
            return false;
        if (this.taskGroup == null) {
            if (other.taskGroup != null)
                return false;
        }
        else if (!this.taskGroup.equals(other.taskGroup))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.firedDatetime == null) ? 0 : this.firedDatetime.hashCode());
        result = prime * result + ((this.taskName == null) ? 0 : this.taskName.hashCode());
        result = prime * result + ((this.taskGroup == null) ? 0 : this.taskGroup.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CronTaskQueue (");

        sb.append(firedDatetime);
        sb.append(", ").append(taskName);
        sb.append(", ").append(taskGroup);

        sb.append(")");
        return sb.toString();
    }
}
