/*
 * This file is generated by jOOQ.
 */
package com.github.chaconne.jooq;


import com.github.chaconne.jooq.tables.CronTaskDetail;
import com.github.chaconne.jooq.tables.CronTaskLog;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>cron_task_detail</code>.
     */
    public final CronTaskDetail CRON_TASK_DETAIL = CronTaskDetail.CRON_TASK_DETAIL;

    /**
     * The table <code>cron_task_log</code>.
     */
    public final CronTaskLog CRON_TASK_LOG = CronTaskLog.CRON_TASK_LOG;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CronTaskDetail.CRON_TASK_DETAIL,
            CronTaskLog.CRON_TASK_LOG
        );
    }
}
