/*
 * This file is generated by jOOQ.
 */
package com.github.chaconne.jooq;


import com.github.chaconne.jooq.tables.CronTaskDetail;
import com.github.chaconne.jooq.tables.CronTaskLog;
import com.github.chaconne.jooq.tables.CronTaskQueue;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>cron_task_detail</code>.
     */
    public static final CronTaskDetail CRON_TASK_DETAIL = CronTaskDetail.CRON_TASK_DETAIL;

    /**
     * The table <code>cron_task_log</code>.
     */
    public static final CronTaskLog CRON_TASK_LOG = CronTaskLog.CRON_TASK_LOG;

    /**
     * The table <code>cron_task_queue</code>.
     */
    public static final CronTaskQueue CRON_TASK_QUEUE = CronTaskQueue.CRON_TASK_QUEUE;
}
